// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxgydompzwjmbgrgxbkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4Z3lkb21wendqbWJncmd4YmtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNTUzMjQsImV4cCI6MjA2MjgzMTMyNH0.tZGmoBQsbYoGgnG31ZaluBzaDl6ww85Z-1Noe905LTY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);